# Generated by Django 5.0.1 on 2024-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='GPU', max_length=100),
            preserve_default=False,
        ),
    ]
