# Generated by Django 5.0.1 on 2024-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(max_length=500),
        ),
    ]
