# Generated by Django 5.0.1 on 2024-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_item_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_url",
            field=models.URLField(unique=True),
        ),
    ]
